Checked for required channels in automove.py
LinsaneFC/RasenBot pull request #39
Opened 2023-08-17 23:08 UTC by stephenlee91

- Created a new helper function to check if the required channels in constantvariables.py exist
- If they do not exist when automove is called, open constantvariables.py and write into the file to set AUTO_MOVE_FLAG to False
- Print to console that required channels do not exist and that AUTO_MOVE_FLAG has been set to False
- Return to exit automove function without running the rest of it

2023-08-17 23:16 UTC, LinsaneFC commented on cogs/moveusers.py
> +    def check_required_channels(self, ctx):
NIT: Let's prefix the function with `_` to mark "private"

2023-08-17 23:30 UTC, LinsaneFC requested changes

2023-08-17 23:30 UTC, LinsaneFC commented on cogs/moveusers.py
> +
NIT: Why newline?

2023-08-17 23:30 UTC, LinsaneFC commented on cogs/moveusers.py
> +                file.truncate()
Need to close the file.

2023-08-17 23:30 UTC, LinsaneFC commented on cogs/moveusers.py
> +            with open("constantvariables.py", "r+") as file:
Should generally put opening files in try/except in case of FileNotExistError

2023-08-17 23:52 UTC, LinsaneFC commented on cogs/moveusers.py
> +            except Exception as e:
Catch alls are not good

2023-08-17 23:52 UTC, LinsaneFC approved these changes

2023-08-18 01:07 UTC, asturrus approved these changes

2023-08-18 01:11 UTC, merged